### ISSUE TITLE
Autostart after logon

### ISSUE THREAD

**Issue by dirkschreib** [dirkschreib/SilentStudio#1]

**Comment by MiroIsNot1337** [comment]
Same here, I would love to have this function! If possible, in an executable app. Thank you for thinking about this.

**Comment by dirkschreib** [comment]
I'll probably create a small UI App. This can be used with the "normal" "Login items".

**Comment by dirkschreib** [comment]
The compiled versions of SilentStudioMenu or SilentStudio can be used in the "Login Items" (Anmeldeobjecte in German) section of the Settings app
