### ISSUE TITLE
Does not compile on 15.1

### ISSUE THREAD

**Issue by kurausus** [dirkschreib/SilentStudio#12]
Hi. At long last I tried to compile it, but it does not work. I get the following error: 

`failed to build module 'CoreFoundation'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.7.43 clang-1600.0.25.3)', while this compiler is 'Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)'). Please select a toolchain which matches the SDK.`

I tried my best and chatgpt could not help me either...

**Comment by dirkschreib** [comment]
I'm working on macOS Sequoia 15.1 with Xcode 16.1 and can't reproduce your problem. The newer Swift compiler generate a warning because I made `Dictionary` `RawRepresentable` but it will still work.

**Comment by kurausus** [comment]
Wow, what a fast reply. Thank you so much! I was just about to write again that after some fiddling I was able to compile it successfully with this command:

`xcrun --sdk macosx swiftc SilentStudio.swift IOServiceConnection.swift -o SilentStudio`

Obviously some problem on my configuration.
