### ISSUE TITLE
Temperature display in the menu bar

### ISSUE THREAD

**Issue by MiroIsNot1337** [dirkschreib/SilentStudio#3]
Should you decide to turn the script into an app, I would love it if the main temperature that is currently displayed in the terminal could be also shown in the menu bar (like, for example with Macs Fan Control).

PS. I am very happy with the script as it is right now. Wake/sleep recognition would be my number 1 request.

**Comment by lcrivell** [comment]
I adapted Dirk's script into an app, you may try it here: https://www.dropbox.com/sh/7783hykwzatbnz7/AADncVXMxKEfV-aN4Pg98xgua?dl=0

**Comment by MiroIsNot1337** [comment]
Wow, that was fast. How do I run this app? I have downloaded the folder, but do not see anything that's executable (with a simple click).

**Comment by lcrivell** [comment]
True, I didn't make a package of it yet. You may want to open the xcodeproj with XCode and compile & run from here.

**Comment by MiroIsNot1337** [comment]
Unfortunately, I am such a noob that Dirk had to explain to me how to make even his script executable (chmod +x). I fear compiling anything is beyond me. I only found my way here because I was searching how to deactivate the fan.

**Comment by MiroIsNot1337** [comment]
@lcrivell I managed to run it from within XCode, but I can't install the helper. I let XCode perform some suggested changes, but that didn't make a difference. The menu bar symbol works and fan speed is updated, but I think the problem with the helper prevents it from changing the fan speed. In any case I do not have the knowledge to compile the app with XCode. It would be a huge help if you could do it.

<img width="389" alt="Screenshot 17 01 2023 um 12 39 58 PM" src="https://user-images.githubusercontent.com/122529727/212889955-d3f70dd4-20b9-4e58-8b4f-422e7e69dae3.png">

**Comment by lcrivell** [comment]
Let me have a look. Quite busy these days, will try this weekend. Sorry about issues. On 17 Jan 2023, at 12:47, MiroIsNot1337 ***@***.***> wrote:﻿
@lcrivell I managed to run it from within XCode, but I can't install the helper. I let XCode perform some suggested changes, but that didn't make a difference. The menu bar symbol works and fan speed is updated, but I think the problem with the helper prevents it from changing the fan speed. In any case I do not have the knowledge to compile the app with XCode. It would be a huge help if you could do it.

**Comment by MiroIsNot1337** [comment]
Thank you and no worries, I am already amazed that my request has already been fulfilled by someone. If I can be greedy, I would like the ability to choose temperatures/fan speeds from a simple menu or add them via a text configuration file and the ability to autostart the app. But I am already very happy to have Dirk's script!

**Comment by dirkschreib** [comment]
I implemented a small menu app which uses the script. This need a little bit more polishing before publishing ;-).

**Comment by MiroIsNot1337** [comment]
Very happy to hear that!

**Comment by MiroIsNot1337** [comment]
Thank you! When trying to run the app, this happens:
<img width="283" alt="Screenshot 17 01 2023 um 21 41 11 PM" src="https://user-images.githubusercontent.com/122529727/213008852-4c9bd197-dbab-4beb-a9cd-bb6a304c04f3.png">
Rough translation: Apple can't search the .app for viruses, so it won't open it. Also says I should ask the developer for help.

Unfortunately, same as before when I try to run from within Xcode. This time, I have more screenshots for you.
<img width="1143" alt="Screenshot 17 01 2023 um 21 43 38 PM" src="https://user-images.githubusercontent.com/122529727/213009063-97383274-8632-44ff-9226-9d6a65cf1907.png">
There were also 2 red warnings in the beginning, but with the options you see on the right, I can run the app. It was the same with the old version. Since the main problem seems to be the helper part, I have also created a screenshot of one of the errors connected to that.

<img width="968" alt="Screenshot 17 01 2023 um 21 45 20 PM" src="https://user-images.githubusercontent.com/122529727/213009374-29f106d6-967e-42a8-b854-f7d5bc5e70cf.png">

**Comment by lcrivell** [comment]
Which macOS version are you using ?Also, after you get the first error message when starting the app, can you go in settings, security and select Open Anyway (Trotzdem öffnen ?). On 17 Jan 2023, at 21:50, MiroIsNot1337 ***@***.***> wrote:﻿
Thank you! When trying to run the app, this happens:

Rough translation: Apple can't search the .app for viruses, so it won't open it. Also says I should ask the developer for help.
Unfortunately, same as before when I try to run from within Xcode. This time, I have more screenshots for you.

There were also 2 red warnings in the beginning, but with the options you see on the right, I can run the app. It was the same with the old version. Since the main problem seems to be the helper part, I have also created a screenshot of one of the errors connected to that.

**Comment by MiroIsNot1337** [comment]
I use Ventura 13.1 with the latest updates installed. I don't see the option to click on settings anywhere when opening the app.

**Comment by dirkschreib** [comment]
I wrote a small SwiftUI app and doesn't wanted to use the "authorization route". The alternative is to separate the part which requires root permissions to a separate app (which I already had). This might not be the "best practice" but I wanted to keep it as simple as possible.

**Comment by MiroIsNot1337** [comment]
I'll be happy with anything that works, really. Thank you both for working on this when you clearly already have solutions for yourselves!

**Comment by dirkschreib** [comment]
@lcrivell I don't mind that you copied the source code. Actually I really like it if someone can make use of it and create something even better. That's the reason for the permissive MIT license. May I friendly remind you to retain the copyright notice?

**Comment by dirkschreib** [comment]
SilentStudioMenu shows the temperature and fan speed in the menu bar. Further improvements should be separate issues.
