### ISSUE TITLE
fan speed change after standby does not work

### ISSUE THREAD

**Issue by MiroIsNot1337** [dirkschreib/SilentStudio#7]
SilentStudioMenu correctly detected my Mac Studio waking up from standby and even turned off the fan briefly, however, with the next temperature update, it turned the fan on despite being well below 60°C. I started up a stress test afterwards and the fan then stayed on until 50°C at which point it was immediately turned off. It then behaved completely normal and turned the fan on when above 60°C and off once below 50. However, after standby it always turns on the fan until the 50°C threshhold is reached. All of this is with 'automatic fan' enabled in the menu.

<img width="398" alt="Screenshot 18 01 2023 um 23 11 15 PM" src="https://user-images.githubusercontent.com/122529727/213306778-1a65aaa0-49b3-482f-a756-500492d41f26.png">

<img width="339" alt="Screenshot 18 01 2023 um 23 14 47 PM" src="https://user-images.githubusercontent.com/122529727/213307119-8ef166d1-aee8-47e3-ab08-5308aec5e06f.png">

**Comment by dirkschreib** [comment]
I‘ll have a look. I can‘t see any „Set fans to AUTO rpm“ in your log. Currently not sure what caused this. 
BTW: I‘ll add the timestamps to SilentStudioMenu as well…

**Comment by MiroIsNot1337** [comment]
Sorry, I went a bit all over the place with the topics. To summarize: Setting a temperature range or manually adding all temperature values works and the fan stays off after standby.

**Comment by dirkschreib** [comment]
I'll close this for now. Please report again if something doesn't work
